WITH DOCTOR AS (
SELECT NAME,
       ROW_NUMBER()OVER(ORDER BY NAME) AS RN
FROM OCCUPATIONS
WHERE OCCUPATION = 'DOCTOR'
),
PROFESSOR AS (
SELECT NAME,
       ROW_NUMBER()OVER(ORDER BY NAME) AS RN
FROM OCCUPATIONS
WHERE OCCUPATION = 'PROFESSOR'
),
SINGER AS (
SELECT NAME,
    ROW_NUMBER()OVER(ORDER BY NAME) AS RN
FROM OCCUPATIONS
WHERE OCCUPATION = 'SINGER'
),
ACTOR AS (
SELECT NAME,
    ROW_NUMBER()OVER(ORDER BY NAME) AS RN
FROM OCCUPATIONS
WHERE OCCUPATION = 'ACTOR'
)
SELECT
    D.NAME,
    P.NAME,
    S.NAME,
    A.NAME
FROM PROFESSOR P
LEFT JOIN DOCTOR D USING(RN)
LEFT JOIN SINGER S USING(RN)
LEFT JOIN ACTOR A USING(RN)